added circleci config.yml
andela/hc-bulls pull request #2
Opened 2018-04-22 18:30 UTC by zenjutahi

#156913221 Integrate Circle CI for continuous integration and link it with Heroku

2018-04-23 10:01 UTC, jimmykamau commented on .circleci/config.yml
> +        branch: develop
Change this to master

2018-04-23 11:13 UTC, jimmykamau requested changes
`production` configuration is pointing to the wrong app

2018-04-23 11:13 UTC, jimmykamau commented on .circleci/config.yml
> +          appname: hc-bulls
Change this to hc-bullss

2018-04-23 11:56 UTC, jimmykamau requested changes
Deployment also won't work until you add the configuration described here: https://circleci.com/docs/2.0/deployment-integrations/#heroku
I've already set the API_KEY and APP_NAME variables.

2018-04-25 03:24 UTC, zenjutahi commented
I setup the deployment job

2018-04-25 06:30 UTC, Bonifase approved these changes
Great job! All check are passing, I hope you have configured it with Heroku

2018-04-25 06:32 UTC, Bonifase commented
@zenjutahi , I will need your assistance on how to fix the circleci badge in order to do away with the fails.

2018-04-25 08:38 UTC, ghost approved these changes

2018-04-26 09:26 UTC, jimmykamau approved these changes

2018-04-26 09:26 UTC, merged