#[#156991533] Integrate Coveralls
andela/hc-bulls pull request #3
Opened 2018-04-23 16:31 UTC by zenjutahi

2018-04-23 19:40 UTC, jimmykamau requested changes
Did you branch off `develop` or the branch you had been previously working on?

2018-04-24 12:22 UTC, zenjutahi commented
I branched from my local `develop`, not the same branch i did circleci on, i just added the necessary file configurations to ensure it passes

2018-04-25 03:34 UTC, zenjutahi commented
resolved conflicts and unnecessary changes in unexpected files

2018-04-25 06:26 UTC, Bonifase approved these changes
The build is fine, can be merged to develop

2018-04-25 06:32 UTC, murageden commented
The task is complete and build is successfull and can be merged

2018-04-25 07:18 UTC, Collins33 approved these changes

2018-04-25 08:36 UTC, ghost approved these changes
The build is successful. Coveralls badge is showing test coverage okay

2018-04-25 10:47 UTC, zenjutahi commented
I changed coveralls.yml

2018-04-25 11:37 UTC, alexmochu approved these changes

2018-04-30 14:04 UTC, zenjutahi commented
revolved conflict in README.md and setup coveralls badge.

2018-05-02 09:33 UTC, jimmykamau approved these changes

2018-05-02 09:33 UTC, jimmykamau commented on README.md
> +[![Coverage Status](https://coveralls.io/repos/github/andela/hc-bulls/badge.svg?branch=ft-Integrate-Coveralls%23156991533)](https://coveralls.io/github/andela/hc-bulls?branch=ft-Integrate-Coveralls%2
Point the branch to Develop

2018-05-02 09:34 UTC, merged