Ft fixing api tests #156687690
andela/hc-bulls pull request #9
Opened 2018-04-26 11:54 UTC by Collins33

#### What does this PR do?
Fixing API tests and adding more tests where available
#### Description of Task to be completed?
Completed fixing the tests for the API and adding more tests for the API
#### How should this be manually tested?
Clone the repository and run the tests with ./manage.py tests
#### What are the relevant pivotal tracker stories?
#156687690

2018-04-27 09:06 UTC, jimmykamau requested changes
See comments

2018-04-27 09:06 UTC, jimmykamau commented on .travis.yml
> +    - pip install braintree coveralls mock mysqlclient
This was changed in `develop`. Kindly pull the changes.

2018-04-27 09:06 UTC, jimmykamau commented on .vscode/settings.json
> +{
This folder should be ignored in .gitignore

2018-04-27 09:06 UTC, jimmykamau commented on hc/api/tests/test_badge.py
> +        print(r)
Kindly remove debug code

2018-04-27 09:06 UTC, jimmykamau commented on requirements.txt
> +
Why so many empty lines?

2018-04-27 09:06 UTC, jimmykamau commented on hc/settings.py
> +# variable 'DB'. Travis CI does this .
Unnecessary change

2018-04-27 09:06 UTC, jimmykamau commented on hc/api/tests/test_sendalerts.py
> +        # self.assertEqual(False,result)
Why have these been commented out?

2018-04-27 09:06 UTC, jimmykamau commented on hc/api/tests/test_create_check.py
> +        # self.assertEqual(r["error"], "could not parse request body")
Kindly delete code if it's not needed instead of commenting it out

2018-04-27 09:06 UTC, jimmykamau commented on hc/api/tests/test_create_check.py
> +    ### Test for the assignment of channels NOT DONE
Why isn't this done?

2018-04-27 12:31 UTC, zenjutahi approved these changes

2018-04-30 10:27 UTC, jimmykamau requested changes
Incorrect PR naming

2018-04-30 11:00 UTC, Collins33 commented
Renamed the PR

2018-05-02 09:48 UTC, jimmykamau approved these changes

2018-05-02 11:21 UTC, merged